import { useEffect, useState } from "react";
import classes from "./upload-form.module.sass";
import classnames from "classnames";

import { FaUserCog, FaProjectDiagram } from "react-icons/fa";
import FileUpload from "../file-upload/file-upload.component";

const newLine =  (idx) => <div className={classnames(classes.row)}>
<div className={classes.imageBatchNum}>
  <div className={classes.lightgrey}>Image Batch</div>
  <div>{idx + 1}</div>
</div>
<div className={classes.imageBatchInfo}>
  <div className={classnames(classes.col, classes.lightpurple)}>
    <div>TISSUE</div>
    <div className={classes.row}>
      <div className={classes.col}>
        <label>*Species</label>
        <input name="species" type="text" id="species" />
      </div>
      <div className={classes.col}>
        <label>*Species</label>
        <input name="species" type="text" id="species" />
      </div>
      <div className={classes.col}>
        <label>Strain</label>
        <input name="species" type="text" id="species" />
      </div>
      <div className={classes.col}>
        <label>Animal Treatment</label>
        <input name="species" type="text" id="species" />
      </div>
      <div className={classes.col}>
        <label>*Organ</label>
        <input name="species" type="text" id="species" />
      </div>
    </div>
  </div>
  <div className={classnames(classes.col, classes.lightyellow)}>
    <div>IMAGE METADATA</div>
    <div className={classes.row}>
      <div className={classes.col}>
        <label>*Slice Thickness(um)</label>
        <input name="species" type="text" id="species" />
      </div>
      <div className={classes.col}>
        <label>*Pixel Size(um)</label>
        <input name="species" type="text" id="species" />
      </div>
      <div className={classes.col}>
        <label>*Anatomical Region</label>
        <input name="species" type="text" id="species" />
      </div>
      <div className={classes.col}>
        <label>Struceture Detail</label>
        <input name="species" type="text" id="species" />
      </div>
      <div className={classes.col}>
        <label>*Organ</label>
        <input name="species" type="text" id="species" />
      </div>
    </div>
  </div>
  <div className={classnames(classes.col, classes.lightblue)}>
    <div>UPLOAD FILES</div>
    <div style={{ width: "100%" }}>
      <FileUpload />
    </div>
  </div>
</div>
</div>

const UploadForm = () => {
  const buttonStyling =
    "p-5 rounded-md bg-blue-600 font-semibold text-white flex items-center gap-1 hover:bg-blue-800";

  const [divs, setDivs] = useState([<div key="0" >{newLine(0)}</div>]);

  const addNewDiv = () => {
    setDivs([...divs, <div key={divs.length} >{newLine(divs.length)}</div>]);
  };

  return (
    <div className={classes.wrapper}>
      <div className={classnames(classes.row, classes.lightgrey)}>
        <div className={classes.row2}>
          <div>
            <FaUserCog />{" "}
          </div>
          <div>Use rName: </div>
          <div>Email: </div>
        </div>
        <div className={classes.row2}>
          <div>
            <FaProjectDiagram />
          </div>
          <div>Project Name: </div>
        </div>
      </div>
      <div className={classes.uploadForm}>
       
        {divs.map((div, index) => (
          <div key={index}>{div}</div>
        ))}
        <div
          className={classnames(
            classes.col,
            classes.lightgrey,
            classes.newbatch
          )}
          style={{ padding: "20px 0" }}
          onClick={addNewDiv}
        >
          + Add new batch
        </div>
      </div>
      <div>
        <input type="checkbox" /> Agree: This web application tool is designed
        to assist academic institutes in quantifying cells for research and
        educational purposes. While we strive to ensure the accuracy and
        reliability of the results, we cannot guarantee the absolute precision
        of the calculations. The accuracy of cell counting may vary based on
        image quality and user input. The tool is not a substitute for
        professional medical or scientific analysis. Users are encouraged to
        verify the results independently for critical applications. The
        developers of this tool disclaim any responsibility for the accuracy,
        completeness, or reliability of the results obtained. Users are solely
        responsible for the interpretation and use of the data generated by this
        application. By using this web application, you agree to these terms and
        acknowledge the limitations of the tool.
      </div>
      <div className="flex justify-end">
        <button className={buttonStyling}>Submit</button>
      </div>
    </div>
  );
};

export default UploadForm;
